// Writes the contract ABIs the app reads, straight out of the compiled
// artifacts next door.
//
//   npm run abi
//
// Not hand-copied. An ABI typed out by hand drifts the first time a function is
// renamed, and the failure is a page that silently shows nothing rather than an
// error anybody notices. This regenerates from ../contracts/out, which is built
// by `npm run compile` in that directory.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(dirname(fileURLToPath(import.meta.url)));
const artifacts = join(here, "..", "contracts", "out");
const outDir = join(here, "src", "lib", "abi");

/** Only what the app calls. A smaller ABI is a smaller bundle and a shorter thing to read. */
const WANTED = {
  Snowly: [
    "hook",
    "glacier",
    "treasury",
    "driftCount",
    "driftAt",
    "latest",
    "driftsOf",
    "driftOfPool",
    "poolKeyOf",
    "poolIdOf",
    "fieldStats",
    "supplyShares",
    "launch",
    "FIXED_SUPPLY",
    "POOL_BPS",
    "SUPPLY_WALLET_BPS",
    "LP_FEE",
  ],
  SnowHook: ["FEE_BPS", "CREATOR_BPS", "BPS", "owed", "creatorOf", "withdraw", "withdrawMany", "quoteFee", "treasury"],
  Glacier: ["compactionOf", "compactedLiquidity"],
  SnowToken: ["name", "symbol", "decimals", "totalSupply", "balanceOf", "toGlacier", "toSupplyWallet", "supplyWallet"],
};

if (!existsSync(artifacts)) {
  console.error(`no artifacts at ${artifacts}`);
  console.error("Run `npm run compile` in ../contracts first — out/ is built, not committed.");
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });

const camel = (name) => name[0].toLowerCase() + name.slice(1);

for (const [contract, names] of Object.entries(WANTED)) {
  const path = join(artifacts, `${contract}.json`);
  if (!existsSync(path)) {
    console.error(`${contract}.json is missing — recompile the contracts`);
    process.exit(1);
  }

  const { abi } = JSON.parse(readFileSync(path, "utf8"));
  const kept = abi.filter((entry) => entry.type !== "function" || names.includes(entry.name));

  const missing = names.filter((name) => !abi.some((e) => e.type === "function" && e.name === name));
  if (missing.length > 0) {
    console.error(`${contract} no longer has: ${missing.join(", ")}`);
    console.error("The app calls these. Fix the list in this script, or the contract.");
    process.exit(1);
  }

  const variable = `${camel(contract)}Abi`;
  writeFileSync(
    join(outDir, `${camel(contract)}.ts`),
    `// Generated by scripts/abi.mjs from ../contracts/out/${contract}.json — do not edit.\n` +
      `export const ${variable} = ${JSON.stringify(kept)} as const;\n`,
  );

  const functions = kept.filter((e) => e.type === "function").length;
  console.log(`${variable.padEnd(16)} ${functions} functions, ${kept.length} entries`);
}

console.log(`\nwritten to src/lib/abi/`);
