// Compiles the Hoodpad contracts with solc-js and writes the ABIs the web app
// imports, so the frontend can never drift from the deployed interface.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const solc = require("solc");

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "src");
const outDir = join(here, "out");
const abiDir = resolve(here, "..", "hoodpad", "src", "lib", "abi");

function collectSources(dir, prefix = "") {
  const sources = {};
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) Object.assign(sources, collectSources(join(dir, entry.name), rel));
    else if (entry.name.endsWith(".sol")) sources[rel] = { content: readFileSync(join(dir, entry.name), "utf8") };
  }
  return sources;
}

function findImports(path) {
  try {
    if (path.startsWith("@")) return { contents: readFileSync(require.resolve(path, { paths: [here] }), "utf8") };
    return { contents: readFileSync(join(srcDir, path), "utf8") };
  } catch (error) {
    return { error: `not found: ${path} (${error.message})` };
  }
}

const input = {
  language: "Solidity",
  sources: collectSources(srcDir),
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: "cancun",
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object", "evm.deployedBytecode.object"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input), { import: findImports }));

const diagnostics = output.errors ?? [];
for (const d of diagnostics) console.error(d.formattedMessage.trimEnd());
if (diagnostics.some((d) => d.severity === "error")) {
  console.error("\ncompile failed");
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });
mkdirSync(abiDir, { recursive: true });

const EXPORTED = {
  "HoodpadFactory.sol": "HoodpadFactory",
  "PositionLocker.sol": "PositionLocker",
  "HoodToken.sol": "HoodToken",
};

const limit = 24576; // EIP-170 deployed-bytecode ceiling
for (const [file, name] of Object.entries(EXPORTED)) {
  const artifact = output.contracts[file][name];
  writeFileSync(join(outDir, `${name}.json`), JSON.stringify(artifact, null, 2));

  const size = artifact.evm.deployedBytecode.object.length / 2;
  const status = size > limit ? "OVER EIP-170 LIMIT" : "ok";
  console.log(`${name.padEnd(16)} ${String(size).padStart(6)} bytes deployed  ${status}`);
  if (size > limit) process.exitCode = 1;

  const constName = `${name.replace(/^./, (c) => c.toLowerCase())}Abi`;
  writeFileSync(
    join(abiDir, `${name.replace(/^./, (c) => c.toLowerCase())}.ts`),
    `// Generated by contracts/compile.mjs — do not edit by hand.\n` +
      `export const ${constName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
}

console.log(`\nABIs written to ${abiDir}`);
